name: Publish Notes To Web

on:
  push:
    branches:
      - master
      - org-roam
      - org-roam-gha

env:
  AWS_DEFAULT_REGION: us-west-2
  BUCKET_NAME: www.ethanp.dev
  DOCKER_IMAGE: maker2413/orgroampublish
  DOCKER_TAG: latest

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Pull Image
        run: |
          docker pull $DOCKER_IMAGE:$DOCKER_TAG

      - name: Run Container
        run: |
          docker run --rm -v $(pwd):/opt/OrgFiles $DOCKER_IMAGE:$DOCKER_TAG

      - name: Upload to S3
        run: |
          aws s3 cp web-site s3://$BUCKET_NAME/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
