name: Publish Notes To Web

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-west-2
  BUCKET_NAME: www.ethanp.dev
  DOCKER_IMAGE: maker2413/orgroampublish
  DOCKER_TAG: latest

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Publish Org Files
        uses: maker2413/OrgRoamPublish@38e421dac721e2abcc10363fc1db04f87ddc8a48
        with:
          args: publish.el

      - name: Upload to S3
        run: |
          aws s3 sync WebSite s3://$BUCKET_NAME/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
